#DEFINES+=PROJECT_CONF_H=\"project-conf.h\"
#PROJECT_SOURCEFILES += stub-rdc.c

CONTIKI_PROJECT = wimea-ict-rss2
APPS=serial-shell

all: $(CONTIKI_PROJECT) 

CONTIKI = ../../../..

#CONTIKI_WITH_RIME = 1
include $(CONTIKI)/Makefile.include
